# Generated by Django 4.1 on 2024-02-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_listing_category_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_biggest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
